CVproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),                         # Админка Django
    path('', include('cvapp.urls')),                         # Основной функционал (резюме и шаблоны)
    path('salary/', include('SalaryPredictionApp.urls')),    # Модуль прогнозов зарплат
    path('accounts/', include('accounts.urls')),             # Регистрация / логин / аккаунты
]

# Подключаем обработку медиафайлов (для изображений шаблонов и профилей)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('reset_password_validate/<uidb64>/<token>/',
         views.reset_password_validate, name='reset_password_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),

    path('profile/', views.profile_view, name='profile'),
    path('<username>/', views.profile_view, name='userprofile'),
    path('profile/edit', views.profile_edit_view, name='profile-edit'),
    path('profile/delete', views.profile_delete_view, name='profile-delete'),
    path('profile/registercreate/', views.profile_edit_view,
         name='profile-registercreate'),
]

cvapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('select-template/', views.SelectTemplate.as_view(), name="select_template"),
    path('resumeTemplate/', views.Accept.as_view(), name='accept'),
    path('list/', views.list, name="list"),
    path('list/<int:id>/', views.UserDetail, name="viewing"),
    path('resume/<int:template_id>/', views.resume, name="resume"),
    path('update/<int:id>/', views.update_form, name="update"),
    path('delete/<int:id>/', views.delete_form, name="deleteform"),
    path('prediction/', views.predict, name="predict"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.templatetags.static import static


class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("Пользователь должен иметь адрес электронной почты")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email,
            password=password,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    objects = MyAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


class UserProfile(models.Model):
    userprofile = models.OneToOneField(Account, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars/', null=True, blank=True)
    realname = models.CharField(max_length=20, null=True, blank=True)
    location = models.CharField(max_length=20, null=True, blank=True)  # Исправлено с 'localtion' на 'location'
    bio = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.userprofile)

    @property
    def avatar(self):
        try:
            avatar = self.image.url
        except:
            avatar = static('assets/images/UserProfile.png')
        return avatar

    @property
    def name(self):
        if self.realname:
            name = self.realname
        else:
            name = self.userprofile.username
        return name

accounts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Account, UserProfile


class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['userprofile']
        labels = {
            'realname': 'Name'
        }
        widgets = {
            'image': forms.FileInput(),
            'bio': forms.Textarea(attrs={'rows': 3})
        }


class RegisterationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name',
                  'phone_number', 'email', 'password']

    def clean(self):
        cleaned_data = super(RegisterationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Password does not match!")

    def __init__(self, *args, **kwargs):
        super(RegisterationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Last Name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter Phone Number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Email Address'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
import logging
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegisterationForm, ProfileForm
from .models import Account, UserProfile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator

# Логгер для отслеживания ошибок
logger = logging.getLogger(__name__)

# Register view
def register(request):
    if request.method == "POST":
        form = RegisterationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            user = Account.objects.create_user(
                first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.phone_number = phone_number
            user.save()

            # User activation email
            current_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])

            try:
                send_email.send()  # Отправка email
            except Exception as e:
                logger.error(f"Error sending email to {email}: {e}")  # Логируем ошибку
                messages.error(request, 'There was an error sending the activation email.')
                return redirect('register')  # Перенаправление при ошибке

            messages.success(request, 'Please verify your email to activate your account.')
            return redirect('/accounts/login/?command=verification&email=' + email)
    else:
        form = RegisterationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)


# Login view
def login_user(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Invalid email or password.')
            return redirect('login')

    return render(request, 'accounts/login_user.html')


# Logout view
@login_required(login_url='login')
def logout_user(request):
    logout(request)
    messages.success(request, 'You have logged out successfully.')
    return redirect('login')


# Account activation view
def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account has been activated successfully!')
        return redirect('login')
    else:
        messages.error(request, 'Invalid activation link!')
        return redirect('register')


# Forgot password view
def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email=email)

            current_site = get_current_site(request)
            mail_subject = 'Reset your password'
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])

            try:
                send_email.send()  # Отправка email
            except Exception as e:
                logger.error(f"Error sending reset password email to {email}: {e}")
                messages.error(request, 'There was an error sending the reset password email.')
                return redirect('forgotPassword')

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('login')
        else:
            messages.error(request, 'Account does not exist with this email address.')
            return redirect('forgotPassword')

    return render(request, 'accounts/forgotPassword.html')


# Password reset validation view
def reset_password_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password.')
        return redirect('resetPassword')
    else:
        messages.error(request, 'This link has expired or is invalid.')
        return redirect('login')


# Password reset view
def resetPassword(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Your password has been successfully reset!')
            return redirect('login')
        else:
            messages.error(request, 'Passwords do not match.')
            return redirect('resetPassword')
    else:
        return render(request, 'accounts/resetPassword.html')


# Profile view
@login_required
def profile_view(request, username=None):
    if username:
        account = get_object_or_404(Account, username=username)
    else:
        account = request.user

    try:
        profile = account.userprofile
    except UserProfile.DoesNotExist:
        raise Http404("Profile does not exist")

    return render(request, 'accounts/profile.html', {'profile': profile})


# Profile edit view
@login_required
def profile_edit_view(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        raise Http404("Profile does not exist")

    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile')

    if request.path == reverse('profile-registercreate'):
        template = 'accounts/profile_registercreate.html'
    else:
        template = 'accounts/profile_edit.html'

    return render(request, template, {'form': form})


# Profile delete view
@login_required
def profile_delete_view(request):
    user = request.user

    if request.method == 'POST':
        logout(request)
        user.delete()
        messages.success(request, 'Your account has been deleted successfully.')
        return redirect('home')

    return render(request, 'accounts/profile_delete.html')

templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on below link to confirm your registration.
http://{{domain}}{% url 'activate' uidb64=uid token=token %}

If you think it's not you, please ignore this email

{% endautoescape %}

templates/accounts/forgotPassword.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<section class="section-conten padding-y" style="min-height:84vh">

        <div class="card mx-auto" style="max-width: 600px; margin-top:100px; box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset;">
          <div class="card-body">
          <h4 class="card-title mb-4">Forgot Password</h4>
          {% include 'includes/alert.html' %}
          <form action="{% url 'forgotPassword' %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'login' %}" class="float-right">Got password? Login</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
    </section>
{% endblock %}

templates/accounts/login_user.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<section class="section-conten padding-y" style="min-height:84vh">

  {% if request.GET.command == 'verification' %}

  <div class="container ex-auto alert-info text-center" role="alert" style="max-width: 1024px; margin-top: 7rem;">
    Thank you for registering with us , We have sent you a verification email to your email address [{{ request.GET.email }}]
    <br><br>
    Already verified? <a href="{% url 'login' %}">Login</a>
  </div>

  {% else %}

        <div class="card mx-auto" style="max-width: 450px; margin-top:11rem; box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset;">
          <div class="card-body">
          <h4 class="card-title mb-4">Login</h4>
          {% include 'includes/alert.html' %}
          <form action="{% url 'login' %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email">
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name="password">
              </div> <!-- form-group// -->

              <div class="form-group">
                  <a href="{% url 'forgotPassword' %}" class="float-right">Forgot password?</a>

              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->

         <p class="text-center mt-4">Don't have account? <a href="{% url 'register' %}">Sign up</a></p>
         <br><br>
      {% endif %}
    </section>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}


{% block content %}
<div style="margin-top:7rem;">
<div class="container ">
    <div class="card p-4" style="background-color: rgb(204, 204, 255)">
        <div class="text-center d-flex flex-column align-items-center">
            <img class="rounded-circle mb-4" style="width: 9rem; height: 9rem; object-fit: cover;" src="{{profile.avatar}}" alt="Profile Picture" />
            <div class="text-center" style="max-width: 30rem;">
                <h1 style="color:rgb(25, 25, 112); font-weight:bold; font-size:3rem;">{{profile.name}}</h1>
                <div class="text-secondary mb-2 mt-0" ><h3 style="color:rgb(70, 130, 180); font-weight:bold;">{{profile.userprofile.username}}</h3></div>
                <div class="d-flex align-items-center justify-content-center mx-auto">
                    <img class="mr-1" style="height: 2rem; opacity: 0.7; color:rgb(0, 128, 128);" src="https://img.icons8.com/material-outlined/50/000000/marker.png" alt="Location Icon">

                    {% if profile.localtion %}
                    <h5 style="color:rgb(0, 128, 128); ">{{profile.localtion}}</h5>
                    {% else %}
                    <h5 style="color:rgb(0, 128, 128);">Planet Earth</h5>
                    {% endif %}
                </div>
                <div class="my-4">
                    {% if profile.bio %}
                    <h2 style="color:rgb(65, 105, 225); font-weight:bold;">
                    {{profile.bio}}
                    </h2>
                    {% else %}
                    <h2 style="color:rgb(65, 105, 225); font-weight:bold;">
                    Professional
                    </h2>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/accounts/profile_delete.html
{% extends "base.html" %}


{% block content %}
<div class="container mt-4">
    <h1>Delete Account</h1>
    <p>Are you sure you want to delete your account?</p>

    <form method='POST'>
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mt-3">Yes, I want to delete my account</button>
        <a class="btn btn-secondary ml-2" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
</div>
{% endblock %}

templates/accounts/profile_edit.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4 " style="background-color:rgb(167, 199, 231); width:50%; padding:3rem; padding-top:7rem; box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset;">
    <h1 class="mb-3" style="text-align:center; color:rgb(25, 25, 112); font-size:3rem; font-weight:bold;">Edit Profile</h1>
    <div class="text-center d-flex flex-column align-items-center">
        <img id="avatar" class="rounded-circle mb-4" style="width: 9rem; height: 9rem; object-fit: cover;" src="{{ userprofile.avatar }}" alt="Avatar" />
        <div class="text-center" style="max-width: 30rem;">
            <h1 id="realname">{{ userprofile.name }}</h1>
            <div class="text-secondary mb-2 mt-n2">@{{ userprofile.userprofile.username }}</div>
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group mb-3">
            <label for="id_image" ><b>Image:</b></label>
            <input type="file" class="form-control"  name="image" accept="image/*" id="id_image"> <small class="text-danger"></small>
          </div>

          <div class="form-group mb-3  row">
            <label for="id_realname" class="col-sm-2 col-form-label"><b>Name:</b></label>
            <div class="col-sm-10">
             <input type="text" class="form-control" name="realname" value="" maxlength="20" id="id_realname"> <small class="text-danger"></small>
            </div>
          </div>

          <div class="form-group mb-3 row">
            <label for="id_localtion" class="col-sm-2 col-form-label"><b>Localtion:</b></label>
            <div class="col-sm-10">
            <input type="text" class="form-control" name="localtion" value="" maxlength="20" id="id_localtion"> <small class="text-danger"></small>
            </div>
          </div>

          <div class="form-group mb-3 row">
            <label for="id_bio" class="col-sm-2 col-form-label"><b>Bio:</b></label>
            <div class="col-sm-10">
             <textarea name="bio"  class="form-control" cols="40" rows="3" id="id_bio"></textarea> <small class="text-danger"></small>
             </div>
          </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <a class="btn btn-secondary ml-2" style="color:red; font-weight:bold;" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
    <a class="mt-3 d-block " style="font-weight:bold;" href="{% url 'profile-delete' %}">Delete Profile</a>
</div>

<script>
    // This updates the avatar
    const fileInput = document.querySelector('input[type="file"]');

    fileInput.addEventListener('change', (event) => {
        const file = event.target.files[0];
        const image = document.querySelector('#avatar');

        if (file && file.type.includes('image')) {
            const url = URL.createObjectURL(file);
            image.src = url;
        }
    });

    // This updates the name
    const realnameInput = document.getElementById('id_realname');
    const realnameOutput = document.getElementById('realname');

    realnameInput.addEventListener('input', (event) => {
        realnameOutput.innerText = event.target.value;
    });
</script>

{% endblock %}

templates/accounts/profile_registercreate.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-3">Complete your Profile</h1>
    <div class="text-center d-flex flex-column align-items-center">
        <img id="avatar" class="rounded-circle mb-4" style="width: 9rem; height: 9rem; object-fit: cover;" src="{{ user.profile.avatar }}" alt="Avatar" />
        <div class="text-center" style="max-width: 30rem;">
            <h1 id="realname">{{ user.profile.name }}</h1>
            <div class="text-secondary mb-2 mt-n2">@{{ user.username }}</div>
        </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        <a class="btn btn-secondary ml-2" href="{{ request.META.HTTP_REFERER }}">Skip</a>
    </form>
</div>

<script>
    // This updates the avatar
    const fileInput = document.querySelector('input[type="file"]');

    fileInput.addEventListener('change', (event) => {
        const file = event.target.files[0];
        const image = document.querySelector('#avatar');

        if (file && file.type.includes('image')) {
            const url = URL.createObjectURL(file);
            image.src = url;
        }
    });

    // This updates the name
    const realnameInput = document.getElementById('id_realname');
    const realnameOutput = document.getElementById('realname');

    realnameInput.addEventListener('input', (event) => {
        realnameOutput.innerText = event.target.value;
    });
</script>

{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
    <div class="card mx-auto" style="max-width:580px; margin-top:11rem; box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset;">
        <article class="card-body">
            {% include 'includes/alert.html' %}
            <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
            <form action="{% url 'register' %}" method="POST">
                {% csrf_token %}

                <div class="form-row">
                    <div class="col form-group">
                        <label for="first_name">First name</label>
                        {{ form.first_name }}
                        {% if form.first_name.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in form.first_name.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div> <!-- form-group end.// -->
                    <div class="col form-group">
                        <label for="last_name">Last name</label>
                        {{ form.last_name }}
                        {% if form.last_name.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in form.last_name.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div> <!-- form-group end.// -->
                </div> <!-- form-row end.// -->

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="email">Email Address</label>
                        {{ form.email }}
                        {% if form.email.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in form.email.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div> <!-- form-group end.// -->
                    <div class="form-group col-md-6">
                        <label for="phone_number">Phone Number</label>
                        {{ form.phone_number }}
                        {% if form.phone_number.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in form.phone_number.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div> <!-- form-group end.// -->
                </div> <!-- form-row.// -->

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="password">Create password</label>
                        {{ form.password }}
                        {% if form.password.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in form.password.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div> <!-- form-group end.// -->
                    <div class="form-group col-md-6">
                        <label for="confirm_password">Repeat password</label>
                        {{ form.confirm_password }}
                        {% if form.confirm_password.errors %}
                            <div class="alert alert-danger mt-2">
                                {% for error in form.confirm_password.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div> <!-- form-group end.// -->
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Register </button>
                </div> <!-- form-group// -->

                {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-2">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </form>
        </article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="{% url 'login' %}">Log In</a></p>
    <br><br>
</section>

{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

As requested, please click on below link to confirm your registration.
http://{{domain}}{% url 'reset_password_validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email

{% endautoescape %}